project:
  type: website

website:
  title: "NIR-Chemometrics"
  site-url: 'https://quartopub.com/sites/jrcuesta/nir-chemometrics'
  description: "Blog about the use of R chemometric tools for NIR spectroscopy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jrcuesta
      - icon: twitter
        href: https://twitter.com/jrcuesta
      - icon: youtube
        href: https://www.youtube.com/user/jrcuesta1
      - icon: envelope-fill
        href: mailto:cuesta_joseramon@yahoo.es
      - icon: rss
        href: index.xml
      - text: Ressources
        menu: 
          - text: NIR-Quimiometrìa
            href: https://nir-quimiometria.blogspot.com
          - text: R bloggers
            href: https://www.r-bloggers.com
          
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

comments:
  giscus:
    repo: jrcuesta/QUARTO

